### ISSUE TITLE
Wrong attribution of comment in meeting notes

### ISSUE THREAD

**Issue by KevinAmazon** [unifiedstreaming/fmp4-ingest#2]
https://github.com/unifiedstreaming/fmp4-ingest/blob/59f054283dbe88e72842de0e899913c36534b960/conference-calls/notes-fmp4-ingest-8th-jan.txt#L30

While I agree completely with this sentiment, this was raised by Kevin Johns of CenturyLink, not Kevin Moore of AWS.

**Comment by unifiedstreaming** [comment]
Yes thank you, I will edit accordingly
