### ISSUE TITLE
Signal Stop

### ISSUE THREAD

**Issue by KevinCJohns** [unifiedstreaming/fmp4-ingest#5]
The text currently states:
11. When the live stream event is over, after sending the last segment, the encoder or ingest source MUST gracefully end the connection by signalling the stop. The encoder or ingest source MUST wait for the service to return the final response code, and then terminate the connection.

But there is no definition of what is a Stop. Presumably the Stop is a combination of a signal within the encoded stream as well as termination of the application level transfer (e.g., Chunked Transfer Encoding is terminated with a 0 length chunk)?

**Comment by unifiedstreaming** [comment]
I removed this from the spec, as we use short running posts no resources are occupied in case no data is transmitted, stop message may be added to specification but is not that important, i agree current description was not clear enough

**Comment by KevinCJohns** [comment]
I think have an explicit stop of end is worth pursuing. We see customers us our platforms for events and having an explicit stop tells us when an event is over and ready for archive or that when a new event starts we don't append to the previous events recording.

**Comment by unifiedstreaming** [comment]
Ok, to signal the stop we can keep the empty mfra box to signal it, which was there before to signal the stop, this is already implemented in quite a few implementations, do you have another idea of signalling the stop ?
